FROM node:alpine AS builder


RUN apk add --no-cache libc6-compat && corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package*.json ./


RUN pnpm install 

COPY . .


RUN pnpm run build

EXPOSE 3000


CMD ["pnpm", "start"]


