name: CI - Build and Push Docker Images

on:
  push:
    branches: [ akcena14-patch-1 ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v3  

      - name: Login to Docker Hub 
        uses: docker/login-action@v2
        with:
          username: ahmadkarimqureshi
          password: biosphere123

      - name: Build Node.js image (frontend)
        run: docker build ./frontend  -t username/nodejs-app 

      - name: Push Node.js image to Docker Hub (if applicable)
        run: docker push username/nodejs-app

      - name: Build Django image (replace with your Dockerfile path)
        run: docker build ./backend  -t username/django-app 

      - name: Push Django image to Docker Hub (if applicable)
        run: docker push username/django-app

